{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "dnt": "1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "jenkins-timestamper-offset=-39600000; XSRF-TOKEN=tgvm0chatemhls68a0oloisi0d; JWT-SESSION=eyJhbGciOiJIUzI1NiJ9.eyJsYXN0UmVmcmVzaFRpbWUiOjE2MDc5MzM3NjMyNzAsInhzcmZUb2tlbiI6InRndm0wY2hhdGVtaGxzNjhhMG9sb2lzaTBkIiwianRpIjoiQVhaZ09wUEpnQThfbWFJQi1JSDMiLCJzdWIiOiJBWFdiX0hEcEtsX0ZGaEtuNzhmNSIsImlhdCI6MTYwNzkzMjIyMCwiZXhwIjoxNjA4MTkyOTYzfQ.sTHl9NSfsNB5o6jUd0TBG3Mswsn4Fonn_FKfV2vhSF0"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/console/",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/",
  "listenerPath": "/console/*",
  "relativePath": "/console/",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/console/",
  "rawRequestPath": "/console/",
  "remoteAddress": "/127.0.0.1:55450",
  "requestPath": "/console/"
}